"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000
palette = "catppuccin_macchiato"

format = """
[░▒▓](fg:mauve)\
[ $os ](bg:mauve fg:crust)\
[](fg:mauve bg:blue)\
$directory\
[](fg:blue bg:surface0)\
$git_branch\
$git_status\
$git_metrics\
[](fg:surface0 bg:mantle)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](fg:mantle bg:crust)\
$fill\
$cmd_duration\
\n$character"""

[os]
disabled = false
style = "bg:mauve fg:crust"

[os.symbols]
Windows = "󰍲"
Ubuntu = "🦝"
Macos = "󰀵"
Linux = "󰌽"

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "fg:crust bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙 "
Downloads = "󰉍 "
Music = "󰝚 "
Pictures = "󰋩 "

[git_branch]
symbol = ""
style = "bg:surface0"
format = '[[ $branch(:$remote_branch) ](fg:blue bg:surface0)]($style)'

[git_status]
style = "bg:surface0"
format = '[[($all_status$ahead_behind )](fg:blue bg:surface0)]($style)'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged = "[+${count}](fg:green bg:surface0)"
modified = "[~${count}](fg:peach bg:surface0)"
untracked = "[?${count}](fg:sapphire bg:surface0)"
deleted = "[✘${count}](fg:red bg:surface0)"

[git_metrics]
disabled = false
added_style = "fg:green bg:surface0"
deleted_style = "fg:red bg:surface0"
format = '([[+$added]($added_style) [-$deleted]($deleted_style) ](bg:surface0))'

[nodejs]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol ($version) ](fg:blue bg:mantle)]($style)'

[rust]
symbol = ""
style = "bg:mantle"
format = '[[ $version ](fg:blue bg:mantle)]($style)'

[golang]
symbol = ""
style = "bg:mantle"
format = '[[ $version ](fg:blue bg:mantle)]($style)'

[php]
symbol = ""
style = "bg:mantle"
format = '[[ $version ](fg:blue bg:mantle)]($style)'

[python]
symbol = ""
style = "bg:mantle"
format = '[[ $version ](fg:blue bg:mantle)]($style)'

[cmd_duration]
min_time = 2000
format = "[  $duration ](fg:overlay2)"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
